[server]
maxUploadSize = 1024
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#1e88e5"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#e0e0e0"
textColor = "#212121"
font = "sans serif"